DJANGO-FLASK/PatDoc/PatDoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home),
    path('',views.home),
    path('accounts/',include('accounts.urls')),
    path('search/', views.search),
    path('search/book/', views.book),
    path('search/book/home/', views.home),
    path('accounts/appointments/home/', views.home)
    
]

urlpatterns += staticfiles_urlpatterns()

DJANGO-FLASK/PatDoc/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('',views.accounts, name='accounthome'),
    path('login/', views.login, name = 'login'),
    path('register/', views.register, name = 'register'),
    path('dhome', views.dhome, name="dhome"),
    path('appointments/',views.appointments, name="appointments"),
    path('logout/',views.logout, name = "logout")
    
    
]

DJANGO-FLASK/PatDoc/accounts/models.py
from django.db import models

# Create your models here.

DJANGO-FLASK/PatDoc/PatDoc/views.py
from django.http import HttpResponse
from django.shortcuts import render
import requests

def home(request):
    return render(request, 'home.html')
    #return HttpResponse("Welcome")

def book(request):
    if request.method == "POST":
        doctor_email = request.POST['doctor']
        patient_email = request.POST['email']
        name = request.POST['patient']
        age = request.POST['age']
        relation = request.POST['relation']
        date = request.POST['date']
        time = request.POST['time']

        json_data = {
            'doctor': doctor_email,
            'email': patient_email,
            'patient': name,
            'age': age,
            'relation': relation,
            'date': date,
            'time': time
        }
        api_url = "http://localhost:5000/book"
        r = requests.post(url = api_url, json = json_data)
        if r.status_code == 200:
            return render(request, "bookings.html")
        else:
            return render(request, "search.html")

def search(request):
    if request.method == "POST":
        email = request.POST['browser']
        json_data = {
            'email': email
        }
        api_url ="http://localhost:5000/doctor"
        r = requests.post(url =api_url,json=json_data)
        if r.status_code == 200:
            accounts = r.json()
            return render(request, "drinfo.html",{'account':accounts} )
        else:
            msg = r.json['msg']
            return render(request, "search.html", {'msg': msg})
    
    api_url = "http://localhost:5000/doctor"
    r = requests.get(api_url)
    doctors = r.json()
    return render(request, 'search.html',{'doctors':doctors})

DJANGO-FLASK/PatDoc/accounts/views.py
from http.client import HTTPResponse
from django.shortcuts import render, redirect
import requests

def accounts(request):
    return render(request,"accounts/accounts.html")

def dhome(request):
    return render(request, "accounts/dhome.html")

def logout(request):
    del request.session['email']
    del request.session['username']
    request.session['loggedin'] = False
    del request.session['loggedin']
    return redirect("/accounts/")

def appointments(request):
    if request.method == "POST":
        id = request.POST['booking_id']
        time = request.POST['time']
        json_data = {
            'id': id,
            'app_date': time
        }
        api_url = "http://localhost:5000/appointmentstime"
        r= requests.post(url = api_url, json=json_data)
        msg = 'Your appointment for the patient has been successfully booked !'
        if r.status_code == 200:
            return render(request, "accounts/appointments.html",{'msg':msg})
    if not 'email' in request.session:
        return redirect("accounts/")
    else:
        email = request.session['email']
        json_data = {
            'email': email
        }
        api_url = "http://localhost:5000/appointments"
        r = requests.post(url = api_url, json=json_data)
        appointments = r.json()
        return render(request, 'accounts/appointments.html',{'appointments':appointments})


    

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']

        json_data = {
            'email': email,
            'password': password
        }

        api_url = "http://localhost:5000/login"

        r = requests.post(url=api_url, json=json_data)
        
        if r.status_code == 200:
            account=r.json()
            # print(account)
            # print(account['account']['name'])
            request.session['username']=account['account']['name']
            request.session['email']=account['account']['email']
            request.session['loggedin']=True
            print(request.session['email'])
            return redirect('/accounts/dhome')
        else:
            msg = r.json()['msg']
            return render(request,"accounts/login.html",{'msg':msg})
        
    return render(request, "accounts/login.html")

def register(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        hospital = request.POST['hospital']
        add1 = request.POST['add1']
        add2 = request.POST['add2']
        city = request.POST['city']
        pincode = request.POST['pincode']
        time1 = request.POST['time1']
        time2 = request.POST['time2']
        sday = request.POST['sday']
        eday = request.POST['eday']
        password = request.POST['password']
        cpassword = request.POST['cpassword']

        json_data={
            'name': name,
            'email': email,
            'hospital': hospital,
            'add1': add1,
            'add2': add2,
            'city': city,
            'pincode': pincode,
            'time1': time1,
            'time2': time2,
            'sday': sday,
            'eday': eday,
            'password': password,
            'cpassword': cpassword
        }

        api_url = "http://localhost:5000/register"

        r = requests.post(url=api_url, json=json_data)
        # print(r.json())
        # print(r.status_code)
        msg = r.json()['msg']
        if r.status_code == 200:
            return redirect('/accounts/login')
        else:
            return render(request, "accounts/register.html", {'msg':msg})
        
    return render(request, "accounts/register.html")

# Create your views here.

DJANGO-FLASK/PatDoc/accounts/templates/accounts/accounts.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <section class="teams" id="teams">
        <div class="max-width">
            <h2 class="title" style=color:crimson;padding-top:20px;>Welcome Doctor :)</h2>
            <center>
                <div class="carousel owl-carousel">
                    <div class="card">
                        <div class="box" onclick="window.location.href='{% url 'accounts:login' %}';">
                            <img src="{% static 'login.png' %}" alt="">
                            <div class="text">LOGIN</div>
                            <h3>Already a Member ?</h3>
                        </div>
                    </div>
                    <div class="card">
                        <div class="box" onclick="window.location.href='{% url 'accounts:register' %}';">
                            <img src="{% static 'register.png' %}" alt="">
                            <div class="text">REGISTER</div>
                            <h3>New Member ?</h3>
                        </div>
                    </div>
                </div>
            </center>
        </div>
    </section>
{% endblock %}

DJANGO-FLASK/PatDoc/accounts/templates/accounts/appointments.html
{% extends "base.html" %}
{% block content %}
<section>
<div class="max-width">
    <div class="search-content">
    <center>
        {% if msg %}
            <p class="notifier-text">{{ msg }}</p>
        {% endif %}
        <table class="appt">
            <tr>
                <th>ID</th>
                <th>Patient Name</th>
                <th>Age</th>
                <th>Appointment Date</th>
                <th>Temporary Time</th>
                <th>Fixed Time</th>
                <th>Submit</th>
            </tr>
            {% for appointment in appointments.appointments %}
            <tr>
                {% if not appointment.app_date %}
                    <form action="{% url 'accounts:appointments' %}" method="post">
                    {% csrf_token %}
                    <td><input type="text" name="booking_id" value="{{appointment.id}}" style="border: 0px; outline: 0px;" size="2" readonly></td>
                    <td>{{appointment.name}}</td>
                    <td>{{appointment.age}}</td>
                    <td>{{appointment.date}}</td>
                    <td>{{appointment.time}}</td>
                    <td><input type="time" name="time" required></td>
                    <td><input type="submit" value="Book" class="apptBook"></td>
                    </form>
                {% else %}
                    <td>{{appointment.id}}</td>
                    <td>{{appointment.name}}</td>
                    <td>{{appointment.age}}</td>
                    <td>{{appointment.date}}</td>
                    <td>{{appointment.time}}</td>
                    <td>{{appointment.app_date}}</td>
                    <td>Booked</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        <a class="search-doctor" href="home/" style="margin-bottom: 200px;">Go to Home page!</a>
    </center>
    </div>
    </div>
</section>
{% endblock content %}

DJANGO-FLASK/PatDoc/accounts/templates/accounts/dhome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="home" id="home">
        <div class="max-width">
            <div class="home-content">
                <div class="text-1">Welcoming the Doctors of Rishi Hospitals</div>
                <div class="text-2">24 Hrs Service</div>
                <div class="text-3"></div>
                
            </div>
        </div>
    </section>
{% endblock %}

DJANGO-FLASK/PatDoc/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="dregister">
        <center>
        <img class="form-img" src="{% static 'avatar.png' %}">
        <h2 class="dregistertitle">Doctor Login</h2>
        {% if msg %}
            <p class="notifier-text">{{ msg }}</p>
        {% endif %}
        <div style="margin-bottom: 40px;"></div>
        <div class="max-width">
            <form class="form-group" action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                <input type="text" class="form-box" name="email" placeholder="Email" required><br>
                <input type="password" class="form-box" name="password" placeholder="Password" required><br>
                <input type="submit" value="Login" class="search-doctor" name="">
            </form>
        </div>
        </center>
        
    </section>
{% endblock %}

DJANGO-FLASK/PatDoc/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="dregister">
        <center>
        <img class="form-img" src="{% static 'avatar.png' %}">
        <h2 class="dregistertitle">Doctor Registration</h2>
        {% if msg %}
            <p class="notifier-text">{{ msg }}</p>
        {% endif %}
        <div style="margin-bottom: 40px;"></div>
        <div class="max-width">
            <form class="form-group" action="{% url 'accounts:register'%}" method="post">
                {% csrf_token %}
                <p>Basic Info:</p><br>
                <input type="text" class="form-box" name="name" placeholder="Name" required><br>
                <input type="text" class="form-box" name="email" placeholder="Email" required><br>
                <input type="text" class="form-box" name="hospital" placeholder="Hospital Name" required><br>
                <p>Hospital Address:</p><br>
                <input type="text" class="form-box" name="add1" placeholder="Address Line 1" required><br>
                <input type="text" class="form-box" name="add2" placeholder="Address Line 2" required><br>
                <input type="text" class="form-box" name="city" placeholder="City name" required><br>
                <input type="text" class="form-box" name="pincode" placeholder="Pincode" required><br>
                <p>Time slots:</p><br>
                <input type="text" class="form-box" name="time1" placeholder="Slot 1 (Ex: 10:00am-2:00pm)" required><br>
                <input type="text" class="form-box" name="time2" placeholder="Slot 2 (Ex: 5:00pm-9:00pm)" required><br>
                <p>Working Days:</p><br>
                <input type="text" class="form-box" name="sday" placeholder="Starting day (Ex: Monday)" required><br>
                <input type="text" class="form-box" name="eday" placeholder="Ending day (Ex: Friday)" required><br>
                <p>Login Credentials:</p><br>
                <input type="password" class="form-box" name="password" placeholder="Password" required><br>
                <input type="password" class="form-box" name="cpassword" placeholder="Confirm Password" required><br>
                <input type="submit" value="Register" class="search-doctor" name="">
            </form>
            </center>
        </div>
    </section>
{% endblock %}

DJANGO-FLASK/PatDoc/accounts/templates/accounts/test.html
        <table class="appt">
            <tr>
                <th>ID</th>
                <th>Patient Name</th>
                <th>Age</th>
                <th>Appointment Date</th>
                <th>Temporary Time</th>
                <th>Fixed Time</th>
                <th>Submit</th>
            <!-- </tr>
            {% for appointment in appointments %}
            <tr>
                {% if not appointment.app_date: %}
                    <form action="{{ url_for('appointments') }}" method="post">
                    <td><input type="text" name="booking_id" value="{{appointment.booking_id}}" style="border: 0px; outline: 0px;" size="2" readonly></td>
                    <td>{{appointment.patient_name}}</td>
                    <td>{{appointment.patient_age}}</td>
                    <td>{{appointment.appt_date}}</td>
                    <td>{{appointment.temp_time}}</td>
                    <td><input type="time" name="time" required></td>
                    <td><input type="submit" value="Book" class="apptBook"></td>
                    </form>
                {% else: %}
                    <td>{{appointment.booking_id}}</td>
                    <td>{{appointment.patient_name}}</td>
                    <td>{{appointment.patient_age}}</td>
                    <td>{{appointment.appt_date}}</td>
                    <td>{{appointment.temp_time}}</td>
                    <td>{{appointment.appt_time}}</td>
                    <td>Booked</td>
                {% endif %}
            </tr> -->
            {% endfor %}
        </table>
        <a class="search-doctor" href="home/" style="margin-bottom: 200px;">Go to Home page!</a>
    </center>
    </div>

DJANGO-FLASK/PatDoc/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rishi Hospitals</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"/>

</head>
<body>
    <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar sticky">
        <div class="max-width">
            <div class="logo"><a href="#">Rishi Hospitals</a></div>
            <ul class="menu">
                <li><a href="/" class="menu-btn">Home</a></li>
                <li><a href="#about" class="menu-btn">About</a></li>
                {% if not 'loggedin' in request.session %}:
                    <li><a href="{% url 'accounts:accounthome' %}" class="menu-btn">Are you a Doctor?</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:appointments' %}" class="menu-btn">Appointments</a></li>
                    <li><a href="{% url 'accounts:logout' %}" class="menu-btn">Logout</a></li>
                {% endif %}
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>
    <div class="Wrapper">
        {% block content %}
        {% endblock %}
    </div>
    <!-- footer section start -->
    <footer>
        <span>Created By <a href="https://www.linkedin.com/in/ravenaa-ramesh-ab66401a6/">Ravenaa</a> </span>
    </footer>
    
    <script src="{% static 'style.js' %} "></script>
</body>
</html>

DJANGO-FLASK/PatDoc/templates/bookings.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
<div class="max-width">
    <div class="search-content">
    <center>
        <img src="{% static 'confirm.png' %}" height="300">
        <h1>Your Appointment has been booked!</h1>
        <p>You will be informed once the hospital fixes your appointment time!</p>
        <a class="search-doctor" href="home/">Go to Home page!</a>
    </center>
    </div>
</div>
</section>
{% endblock content %}

DJANGO-FLASK/PatDoc/templates/drinfo.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="about">
    
    <div class="max-width">
    <h1 class="title">Dr. {{account.account.name}}</h1>
    <br>
    <div class="about-content">
        <div class="column left">
            <table class="doctorInfo">
                <tr>
                    <td>Name:</td>
                    <td>Dr. {{account.account.name}}</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>{{account.account.email}}</td>
                </tr>
                <tr>
                    <td>Hospital:</td>
                    <td>{{account.account.hospital}}</td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td>{{account.account.add1}}<br>{{account.account.add2}}<br>{{account.account.city}}<br>{{account.pincode}}</td>
                </tr>
                <tr>
                    <td>Working Hours:</td>
                    <td>From {{account.account.time1}} to {{account.account.time2}}</td>
                </tr>
                <tr>
                    <td>Working Days:</td>
                    <td>From {{account.account.sday}} to {{account.account.eday}}</td>
                </tr>
              </table>
        </div>
        <div class="column right">
            <img src="{% static 'about.png' %}" alt="">
        </div>
    </div>
    </div>
    <br><br>
    <center>
    <img class="form-img" src="{% static 'avatar.png' %}">
    <h2 class="dregistertitle">Book Appointment</h2>
    <div class="max-width">
        <form class="form-group" action="book/" method="post">
            {% csrf_token %}
            <input type="text" class="form-box" name="doctor" value="{{account.account.email}}" style="display: none;"><br>
            <input type="text" class="form-box" name="patient" placeholder="Name of the Patient" required><br>
            <input type="text" class="form-box" name="age" placeholder="Age of the Patient" required><br>
            <input type="text" class="form-box" name="relation" placeholder="Relationship with the Patient" required><br>
            <input type="text" class="form-box" name="email" placeholder="Your email address" required><br>
            <input type="date" class="form-box" name="date" placeholder="Date of Appointment" required><br>
            <input type="time" class="form-box" name="time" placeholder="Time of Appointment" required><br>
            <p style="font-size: 12px;"><b>Note:</b> Time of Appointment will be confirmed only by the hospital.</p><br>
            <input type="submit" value="Book Appointment" class="search-doctor" name="">
        </form>
        </center>
    </div>
</section>

{% endblock content %}

DJANGO-FLASK/PatDoc/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rishi Hospitals</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"/>

</head>
<body>
    <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar sticky">
        <div class="max-width">
            <div class="logo"><a href="#">Rishi Hospitals</a></div>
            <ul class="menu">
                <li><a href="/" class="menu-btn">Home</a></li>
                <li><a href="#about" class="menu-btn">About</a></li>
                <li><a href="{% url 'accounts:accounthome'%}" class="menu-btn">Are you a Doctor ?</a></li>
                <li><a href="#contact" class="menu-btn">Contact</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>
    
    <section class="home" id="home">
        <div class="max-width">
            <div class="home-content">
                <div class="text-1">Welcome To Rishi Hospitals</div>
                <div class="text-2">24 Hrs Service</div>
                <div class="text-3">Book Your Appointments Here !</div>
                <a href="search/">Book Now</a>
            </div>
        </div>
    </section>
    
    <!-- footer section start -->
    <footer>
        <span>Created By <a href="linkedin.com/in/ravenaa-ramesh-ab66401a6">Ravenaa</a> </span>
    </footer>

    <script src="{% static 'script.js' %}"></script>
</body>
</html>

DJANGO-FLASK/PatDoc/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="search" id="search">
        <center><img class="search-img" src="{% static 'search.png' %}"></center>
        {% if msg %}
          <p class="notifier-text">{{ msg }}</p>
        {% endif %}
        <div class="max-width">
        <div class="search-content">
          <form action="/search/" method="post">
            {% csrf_token %}
            <div class="bar">
                <input class="searchbar" list="browsers" name="browser">
                  <datalist class="dropbox" id="browsers">
                    {% for doctor in doctors.doctors %}
                      <option label="Dr. {{doctor.name}} - {{doctor.hospital}}"  value="{{doctor.email}}">
                    {% endfor %}
                  </datalist>
            </div>
            <br>
            <center>
              <input type="submit" value="Visit Doctor" class="search-doctor">
            </center>
          </form>
        </div>
        </div>
    </section>

{% endblock %}